version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Building book-reviews application"
      - npm run build
post_build:
  commands:
    - mkdir -p $CODEBUILD_ARTIFACTS_DIR/app
    - cp -r build/. $CODEBUILD_ARTIFACTS_DIR/app

artifacts:
  files:
    - '**/*'  # Include the contents of the 'app' directory
  name: BuildArtifact
  base-directory: app  # Set the base directory for artifacts
