version: 0.2

phases:
  build:
    commands:
      - echo "Building book-reviews application"
      - "npm install"
      - "npm run build"
post_build:
  commands:
    - mkdir -p $CODEBUILD_ARTIFACTS_DIR/app  # Create a folder for artifacts
    - cp -r build/* $CODEBUILD_ARTIFACTS_DIR/app  # Copy build output to the artifacts folder

artifacts:
  files: '**/*'
  name: BuildArtifact

